### ISSUE TITLE
Merchant Onboarding Flow

### ISSUE THREAD

**Issue by piyushswain** [nebulab/solidus_bolt#10]
The merchant onboarding flow should be built into the extension.

These are the broad steps of the merchant onboarding process.

1. Bolt Merchant Account Creation
```
As a first step in the adoption journey, merchants will create a merchant account on Bolt.
This will make use of Bolt-hosted UI and the steps will include information verification for their
Solidus Store information as well as acceptance of Bolt’s terms & policies.
```
Solidus should provide a link to the admin user that will take them to the merchant account registration page to make it easier for them to adopt bolt.

2. Payment Processor Addition to Bolt
Once a Bolt merchant account has been created, the merchant will need to connect to a Bolt supported payment processor in order to start receiving orders.

3. Bolt API Key, Publishable Key and Signing Secret Generation
Upon adding the payment processor, Bolt will generate keys required for setting up Bolt on
Solidus, and redirect the merchant back to Solidus.
Solidus will need to ensure that the API Key, Publishable Key and Signing Secret are auto-filled on the merchant’s Solidus Store.

**Comment by DanielePalombo** [comment]
I think this is not valid anymore, same as https://github.com/nebulab/solidus_bolt/issues/14#issuecomment-1095295767
