### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus_bolt#101]
Refresh an expired access_token

Following the [documentation](https://docs.google.com/document/d/1Hsk-ij1c_kO2ctonyfUPgLXMFDlvi3MK77DRbhEXUjI/edit#) provided by bolt, we should provide a service to refresh the bolt access token.
This requires some refactor when the access_token is used because it cannot being retrieved directly from the session, but we should provide a service that refresh it if necessary.

**Comment by DanielePalombo** [comment]
We don't have any specification on how we can refresh an expired access_token.

**Comment by DanielePalombo** [comment]
This is draft documentation around the refresh token. 

https://docs.google.com/document/d/1Hsk-ij1c_kO2ctonyfUPgLXMFDlvi3MK77DRbhEXUjI/edit#

**Comment by Naokimi** [comment]
Since the refresh token call is essentially the same API call to get access token, just with a different payload, would it be possible to modify https://github.com/nebulab/omniauth-bolt/blob/main/lib/omniauth/strategies/bolt.rb#L41 so that it can do either of the calls based on parameters provided?
