### ISSUE TITLE
Add GetAccountDetails Service

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus_bolt#76]
Add a service that retrieves the Account information of a certain user authorized with the access token using the [BOLT GetAccountDetails API](https://help.bolt.com/api-bolt/#tag/Account/operation/GetAccountDetails)

**Comment by piyushswain** [comment]
There are a few authorization headers that this API requires.

`X-API-KEY` - This is clear, we have to use the Bolt API key
`Authorization` - This header requires the `access_token` saved in the session after a user logs in.
`bearerAuth`- The documentation just mentions the following. 

Security Scheme Type | HTTP
-- | --
HTTP Authorization Scheme | bearer

I am not sure what to make of this and what value is this field expecting

**Comment by DanielePalombo** [comment]
We are already using this endpoint [here](https://github.com/nebulab/omniauth-bolt/blob/main/lib/omniauth/strategies/bolt.rb#L71-L87). Maybe you can check it and take some inspiration
