### ISSUE TITLE
Fix `before_action :verify_bolt_request` for SolidusBolt::WebhooksController

### ISSUE THREAD

**Issue by Naokimi** [nebulab/solidus_bolt#79]
the computed_hmac doesn't match the header_hmac and we are unsure why. Need to check with Bolt and ask for guidance

**Comment by DanielePalombo** [comment]
Now that the problem is clear, we can address it into https://github.com/nebulab/solidus_bolt/pull/37

**Comment by Naokimi** [comment]
Fixed in commit 12df15f5b4e4e609ba30463aa8284955cde9009f
