### ISSUE TITLE
Update install login/register button

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus_bolt#84]
There is a new strategy to load the bolt script and login/register button. We have to integrate it following the instruction provided by:

https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/custom-cart-guides/sso-commerce/#how-to-handle-the-request

After the sign in the user will be redirected on `/users/oauth/bolt` endpoint and will have the parameters code, state, scope.
In order to let it work with our SSO we have to change the [request_phase](https://github.com/nebulab/omniauth-bolt/blob/c6eecfd56bb2e81892e13e14850610acb2354269/lib/omniauth/strategies/bolt.rb#L34) on omniauth-bolt and the [code](https://github.com/nebulab/solidus_bolt/blob/b8602971e8ff9e5d1774e72e92bcc67c3baf7dd4/app/assets/javascripts/authorize_account.js#L35) that redirect the user to that page
It should be enough to replace the `authorization_code` with just the `code` work.
In order to verify the authenticity of the account, is required to check also the ID token thought the jwks tokens.

**Comment by DanielePalombo** [comment]
Moved to blocked because we are waiting for instruction how to detect when a shopper finishes logging in or signing up

**Comment by nickhoffman** [comment]
When a shopper finishes logging in or signing up, Bolt will redirect them to the merchant division's OAuth redirect URL. For you, Piyush, and Paolo, that's set to http://localhost:3000/bolt/oauth right now.

**Comment by DanielePalombo** [comment]
@nickhoffman can you add more details about it?

1) I think we should have the ability to make it dynamic because we are using the same credential locally and on the demo site. If this is not possible, do you mind creating another account and setting the redirect URL to http://solidus-bolt-demo.herokuapp.com/bolt/oauth?
2) How it's hard to customize that URL? Can we ask to change it later without too much effort?
3) Usually when the user is redirected, the URL contains parameters that allow to retrieve the user info

**Comment by nickhoffman** [comment]
It makes more sense to create a merchant division for the demo site, which I've done. If you go to https://merchant-sandbox.bolt.com/developers and set the "Division" dropdown to "Demo Site", you'll see the credentials for the new division, which I've already added at https://solidus-bolt-demo.herokuapp.com/admin/bolt/edit

The OAuth redirect URL is easy to change. It's not shown in Merchant Dashboard yet, so you need to ask someone at Bolt to change it for you.

I'll find out which params are added to the OAuth redirect URL and get back to you.

cc @adentong

**Comment by nickhoffman** [comment]
The params are listed [here](https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/custom-cart-guides/sso-commerce/#build-an-oauth-login-endpoint):
- Authorization Code: Use this to get an ID token, as described in the [How to Handle the Request section](https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/custom-cart-guides/sso-commerce/#how-to-handle-the-request).
- State: A random value that must match the previous state value sent to the API. This acts like a CSRF token.
- Scope: Must be `"openid"`.
- Order ID (optional): This is irrelevant to us.

**Comment by DanielePalombo** [comment]
I still have some problems figuring it out.

I see that the only changed value between `demo site` and our personal account is `Division Public ID`, but we are not using it anywhere. I also check the [documentation](https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/custom-cart-guides/sso-commerce/#how-to-handle-the-request) you provided us, but the division ID is not mentioned. I looked for it even in the [technical document](https://docs.google.com/document/d/1HEkkiOXoI2A44eYcenw2HXw2O-IqL4lsoTwJZhkVwpc/edit#heading=h.cunzcjjb9kz) without success.

Assuming that the redirect_url is calculated depending on the domain, Piyush created this [PR](https://github.com/nebulab/solidus_bolt/pull/85), but after the sign-in the user is not redirect to the specified URL.

**Comment by nickhoffman** [comment]
Hm, I see what you mean. Let me ask around and get back to you, @DanielePalombo.

**Comment by DanielePalombo** [comment]
@nickhoffman do you have any updates about it?

**Comment by DanielePalombo** [comment]
Any updates on this issue?

**Comment by DanielePalombo** [comment]
I have an update about the SSO exchange.
Following the latest provided documentation, we should handle the SSO login following these steps:

https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/custom-cart-guides/sso-commerce/#how-to-handle-the-request

The well-known/configuration file is available at https://api-sandbox.bolt.com/.well-known/openid-configuration .

**Comment by DanielePalombo** [comment]
@piyushswain this is not blocked anymore right?
